spring.application.name=QUINDIOFLIX
spring.config.import=optional:file:.env[.properties]

# ── Conexión Oracle ──────────────────────────────────────────────────────────
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=System
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ── JPA / Hibernate ──────────────────────────────────────────────────────────
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ── Jackson ──────────────────────────────────────────────────────────────────
spring.jackson.default-property-inclusion=non_null
