-- 1. Eliminar restricciones circulares (claves foráneas)
ALTER TABLE departamentos DROP CONSTRAINT fk_dept_jefe;

-- 2. Eliminar tablas (en orden inverso a la creación para respetar llaves foráneas)
DROP TABLE pagos CASCADE CONSTRAINTS;
DROP TABLE reportes CASCADE CONSTRAINTS;
DROP TABLE favoritos CASCADE CONSTRAINTS;
DROP TABLE calificaciones CASCADE CONSTRAINTS;
DROP TABLE reproducciones CASCADE CONSTRAINTS;
DROP TABLE episodios CASCADE CONSTRAINTS;
DROP TABLE temporadas CASCADE CONSTRAINTS;
DROP TABLE contenido_relacionado CASCADE CONSTRAINTS;
DROP TABLE contenido_genero CASCADE CONSTRAINTS;
DROP TABLE contenido CASCADE CONSTRAINTS;
DROP TABLE generos CASCADE CONSTRAINTS;
DROP TABLE categorias CASCADE CONSTRAINTS;
DROP TABLE perfiles CASCADE CONSTRAINTS;
DROP TABLE usuarios CASCADE CONSTRAINTS;
DROP TABLE empleados CASCADE CONSTRAINTS;
DROP TABLE departamentos CASCADE CONSTRAINTS;
DROP TABLE planes CASCADE CONSTRAINTS;

-- 3. Eliminar secuencias
DROP SEQUENCE SEQ_PLANES;
DROP SEQUENCE SEQ_DEPARTAMENTOS;
DROP SEQUENCE SEQ_EMPLEADOS;
DROP SEQUENCE SEQ_USUARIOS;
DROP SEQUENCE SEQ_PERFILES;
DROP SEQUENCE SEQ_CATEGORIAS;
DROP SEQUENCE SEQ_GENEROS;
DROP SEQUENCE SEQ_CONTENIDO;
DROP SEQUENCE SEQ_TEMPORADAS;
DROP SEQUENCE SEQ_EPISODIOS;
DROP SEQUENCE SEQ_REPRODUCCIONES;
DROP SEQUENCE SEQ_CALIFICACIONES;
DROP SEQUENCE SEQ_REPORTES;
DROP SEQUENCE SEQ_PAGOS;

-- 4. Opcional: Eliminar Tablespaces (Solo si los vas a volver a crear y tienes permisos SYSTEM)
DROP TABLESPACE ts_repr_2024 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE ts_repr_2025 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE ts_repr_2026 INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE ts_repr_future INCLUDING CONTENTS AND DATAFILES;

DROP MATERIALIZED VIEW mv_contenido_popular;
DROP MATERIALIZED VIEW mv_ingresos_mensuales;

